name: sub

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  schedule:
    - cron: "3 21,0,3,6,9,12,14 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set Timezone
      # You may pin to the exact commit or the version.
      # uses: szenius/set-timezone@dd47655c84241eec2ffa0a855959c16c0920c3c4
        uses: szenius/set-timezone@v1.0
        with:
          # Desired timezone for Windows
          timezoneWindows: "Singapore Standard Time"
      - uses: actions/checkout@v3
      - name: Check out cwr31/sub
        uses: actions/checkout@v3
        with:
          repository: cwr31/sub
          token: ${{ secrets.my_pat }}
      - name: Install requirements
        run: |
          pip3 install -r ./requirements.txt
      - name: Run sub
        run: |
          python3 ./main.py
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVER_TOKEN: ${{secrets.SERVER_TOKEN}}
      - name: Commit And Push
        run: |
          git config --global user.email ariel@arielherself.xyz
          git config --global user.name ariel
          git add .
          git commit -m "scheduled update"
          git pull --rebase
          git push
#      - name: Pushes to cwr31/sub
#        uses: cpina/github-action-push-to-another-repository@main
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.my_pat }}
#        with:
#          source-directory: 'sub'
#          destination-github-username: 'cwr31'
#          destination-repository-name: 'sub'
#          user-email: god@gmail.com
#          target-branch: master
#      - name: Pushes to cwr31/sub
#        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.my_pat }}
#        with:
#          source_folder: 'sub'
#          destination_repo: 'cwr31/sub'
#          destination_folder: 'sub'
#          user_email: 'god@gmail.com'
#          user_name: 'god'
#          commit_msg: 'copy_folder_to_another_repo_action'
      - uses: gautamkrishnar/keepalive-workflow@master
